[package]
name = "bin"
version.workspace = true
edition.workspace = true
authors.workspace = true
[dependencies]
router = { path = "../router" }
tokio = { workspace = true }
config = { path = "../config" }