[workspace]
members = [
    "app",
    "common", "config",
]
resolver = "2"
[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["xu756"]
[workspace.dependencies]
axum = "0.7.5"
log = "0.4.22"
serde_json = "1.0.127"
serde = "1.0.209"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
tower-http = { version = "0.5.2", features = ["cors"] }
once_cell = "1.19.0"
toml = "0.8.19"
dotenv = "0.15.0"
jsonwebtoken = "9.3.0"
sea-orm = { version = "1.0.0-rc.5", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-time", "with-uuid"] }


