[workspace]
members = [
  "configs",
  "screen"
]
resolver = "2"

[workspace.package]
name = "study_rust"
version = "0.1.0"
edition = "2021"
publish = false


[workspace.dependencies]
axum = "0"
tokio = "1"
serde_json = "1.0.108"
serde = "1"
xcap = "0.0.10"
image = "0.25.1"
active-win-pos-rs = "0.8"
once_cell = "1"
toml = "0"
scrap= "0"
ffmpeg-next="7.0.2"
repng = "0"
smol ="2.0.0"
# 计划任务
delay_timer = "0"
reqwest = "0"
user-agent-parser = "0.3"

#  随机数
md5 = "0"
rand = "0"
# 系统信息
sysinfo = "0"
