[package]
name = "config"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
once_cell = { workspace = true }
toml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
dotenv = { workspace = true }